-- MySQL Script generated by MySQL Workbench
-- Thu Apr 20 15:20:02 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema petadoption1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema petadoption1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `petadoption1` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `petadoption1` ;

-- -----------------------------------------------------
-- Table `petadoption1`.`medicalrecord`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `petadoption1`.`medicalrecord` (
  `RecordID` INT NOT NULL AUTO_INCREMENT,
  `PetID` INT NOT NULL,
  `Vaccination` VARCHAR(50) NULL DEFAULT NULL,
  `Treatment` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`RecordID`, `PetID`),
  INDEX `PetID` (`PetID` ASC) VISIBLE,
  CONSTRAINT `medicalrecord_ibfk_1`
    FOREIGN KEY (`PetID`)
    REFERENCES `petadoption1`.`pet` (`PetID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `petadoption1`.`foster`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `petadoption1`.`foster` (
  `FosterID` INT NOT NULL,
  `PetID` INT NOT NULL,
  `FosterName` VARCHAR(50) NOT NULL,
  `FosterPhone` VARCHAR(20) NOT NULL,
  `FosterEmail` VARCHAR(50) NOT NULL,
  `StartDate` DATE NOT NULL,
  `EndDate` DATE NULL DEFAULT NULL,
  `Status` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`FosterID`, `PetID`),
  INDEX `PetID` (`PetID` ASC) VISIBLE,
  CONSTRAINT `foster_ibfk_1`
    FOREIGN KEY (`PetID`)
    REFERENCES `petadoption1`.`pet` (`PetID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `petadoption1`.`shelter`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `petadoption1`.`shelter` (
  `ShelterID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(50) NOT NULL,
  `Address` VARCHAR(100) NOT NULL,
  `Phone` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`ShelterID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `petadoption1`.`pet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `petadoption1`.`pet` (
  `PetID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(50) NOT NULL,
  `Breed` VARCHAR(50) NOT NULL,
  `Age` INT NOT NULL,
  `Gender` VARCHAR(10) NOT NULL,
  `RecordID` INT NOT NULL DEFAULT NULL,
  `ApplicationID` INT NOT NULL DEFAULT NULL,
  `FosterID` INT NOT NULL DEFAULT NULL,
  `ShelterID` INT NOT NULL DEFAULT NULL,
  PRIMARY KEY (`PetID`, `RecordID`, `FosterID`, `ApplicationID`, `ShelterID`),
  INDEX `RecordID` (`RecordID` ASC) VISIBLE,
  INDEX `ApplicationID` (`ApplicationID` ASC) VISIBLE,
  INDEX `FosterID` (`FosterID` ASC) VISIBLE,
  INDEX `ShelterID` (`ShelterID` ASC) VISIBLE,
  CONSTRAINT `pet_ibfk_1`
    FOREIGN KEY (`RecordID`)
    REFERENCES `petadoption1`.`medicalrecord` (`RecordID`),
  CONSTRAINT `pet_ibfk_2`
    FOREIGN KEY (`ApplicationID`)
    REFERENCES `petadoption1`.`adoptionapplication` (`ApplicationID`),
  CONSTRAINT `pet_ibfk_3`
    FOREIGN KEY (`FosterID`)
    REFERENCES `petadoption1`.`foster` (`FosterID`),
  CONSTRAINT `pet_ibfk_4`
    FOREIGN KEY (`ShelterID`)
    REFERENCES `petadoption1`.`shelter` (`ShelterID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `petadoption1`.`staff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `petadoption1`.`staff` (
  `StaffID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(50) NOT NULL,
  `Title` VARCHAR(50) NOT NULL,
  `Phone` VARCHAR(20) NOT NULL,
  `Email` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`StaffID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `petadoption1`.`adoptionapplication`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `petadoption1`.`adoptionapplication` (
  `ApplicationID` INT NOT NULL AUTO_INCREMENT,
  `ApplicantName` VARCHAR(50) NOT NULL,
  `ApplicantEmail` VARCHAR(50) NOT NULL,
  `ApplicantPhone` VARCHAR(20) NOT NULL,
  `Address` VARCHAR(100) NOT NULL,
  `PetID` INT NOT NULL,
  `Status` VARCHAR(20) NOT NULL,
  `StaffID` INT NOT NULL DEFAULT NULL,
  PRIMARY KEY (`ApplicationID`, `PetID`, `StaffID`),
  INDEX `PetID` (`PetID` ASC) VISIBLE,
  INDEX `StaffID` (`StaffID` ASC) VISIBLE,
  CONSTRAINT `adoptionapplication_ibfk_1`
    FOREIGN KEY (`PetID`)
    REFERENCES `petadoption1`.`pet` (`PetID`),
  CONSTRAINT `adoptionapplication_ibfk_2`
    FOREIGN KEY (`StaffID`)
    REFERENCES `petadoption1`.`staff` (`StaffID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `petadoption1`.`donor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `petadoption1`.`donor` (
  `DonorID` INT NOT NULL AUTO_INCREMENT,
  `FirstName` VARCHAR(50) NOT NULL,
  `LastName` VARCHAR(50) NOT NULL,
  `Phone` VARCHAR(20) NOT NULL,
  `Email` VARCHAR(255) NOT NULL,
  `DonationDate` DATE NOT NULL,
  `Amount` DECIMAL(8,2) NOT NULL,
  PRIMARY KEY (`DonorID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `petadoption1`.`veterinarian`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `petadoption1`.`veterinarian` (
  `VetID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(50) NOT NULL,
  `Phone` VARCHAR(20) NOT NULL,
  `Email` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`VetID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
