-- MySQL Script generated by MySQL Workbench
-- Thu Apr  6 22:04:21 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema PetAdoption
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `PetAdoption` ;

-- -----------------------------------------------------
-- Schema PetAdoption
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `PetAdoption` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `PetAdoption` ;

-- -----------------------------------------------------
-- Table `Adopter`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Adopter` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Adopter` (
  `AdopterId` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`AdopterId`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Adoption`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Adoption` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Adoption` (
  `AdoptionID` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`AdoptionID`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Donor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Donor` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Donor` (
  `DonorID` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`DonorID`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Foster`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Foster` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Foster` (
  `FosterID` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`FosterID`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Pet`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pet` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Pet` (
  `PetID` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`PetID`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Shelter`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Shelter` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Shelter` (
  `ShelterId` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`ShelterId`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Staff`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Staff` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Staff` (
  `StaffID` INT NOT NULL,
  PRIMARY KEY (`StaffID`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Veterinarian`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Veterinarian` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Veterinarian` (
  `VeterinarianID` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`VeterinarianID`))
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
